web: python manage.py migrate && gunicorn untitled_football_project.wsgi:application --bind 0.0.0.0:$PORT
worker: celery -A untitled_football_project worker -l info
beat: celery -A untitled_football_project beat -l info
