# Generated by Django 4.2.23 on 2025-09-13 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0004_remove_team_alternate_color_remove_team_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quarter_1", models.IntegerField(default=0)),
                ("quarter_2", models.IntegerField(default=0)),
                ("quarter_3", models.IntegerField(default=0)),
                ("quarter_4", models.IntegerField(default=0)),
                ("overtime", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("week", models.IntegerField(default=0)),
                ("season", models.IntegerField(default=0)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("PRE", "Pre Season"),
                            ("REG", "Regular Season"),
                            ("POST", "Post Season}"),
                        ],
                        default="REG",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NS", "Not Started"),
                            ("Q1", "First Quarter"),
                            ("Q2", "Second Quarter"),
                            ("Q3", "Third Quarter"),
                            ("OT", "Overtime"),
                            ("HT", "Halftime"),
                            ("FT", "Finished"),
                            ("CANC", "Canceled"),
                            ("PST", "Postponed"),
                        ],
                        default="NS",
                        max_length=20,
                    ),
                ),
                (
                    "away_score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_score",
                        to="games.score",
                    ),
                ),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_games",
                        to="teams.team",
                    ),
                ),
                (
                    "home_score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_score",
                        to="games.score",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_games",
                        to="teams.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "game")},
            },
        ),
    ]
