# Generated by Django 4.2.23 on 2025-11-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_rename_gametime_game_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="away_score",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="home_score",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="overtime",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="total_score",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
