# Generated by Django 4.2.23 on 2025-11-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_alter_game_away_score_alter_game_home_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="date",
            field=models.DateField(),
        ),
    ]
