DEPTH_CHART_POSITION_CHOICES = [
    ("C", "Center"),
    ("CB", "Cornerback"),
    ("DB", "Defensive Back"),
    ("DL", "Defensive Line"),
    ("DT", "Defensive Tackle"),
    ("FS", "Free Safety"),
    ("G", "Offensive Guard"),
    ("ILB", "Inside Linebacker"),
    ("K", "Kicker"),
    ("LB", "Linebacker"),
    ("LS", "Long Snapper"),
    ("MLB", "Middle Linebacker"),
    ("NS", "Nose Tackle"),
    ("OLB", "Outside Linebacker"),
    ("P", "Punter"),
    ("QB", "Quarterback"),
    ("RB", "Running Back"),
    ("SS", "Strong Safety"),
    ("T", "Offensive Tackle"),
    ("TE", "Tight End"),
    ("WR", "Wide Receiver"),
]

POSITION_CHOICES = [
    ("DB", "Defensive Back"),
    ("DL", "Defensive Line"),
    ("K", "Kicker"),
    ("LB", "Linebacker"),
    ("LS", "Long Snapper"),
    ("OL", "Offensive Lineman"),
    ("P", "Punter"),
    ("QB", "Quarterback"),
    ("RB", "Running Back"),
    ("TE", "Tight End"),
    ("WR", "Wide Receiver"),
]

STATUS = [
    ("ACT", "Active"),
    ("CUT", "Cut"),
    ("DEV", "Practice Squad"),
    ("INA", "Inactive"),
    ("RES", "Reserve List"),
]