# Generated by Django 4.2.23 on 2026-02-12 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0007_player_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_teams', models.IntegerField(default=10)),
                ('num_rounds', models.IntegerField(default=15)),
                ('user_team_position', models.IntegerField(default=1)),
                ('current_round', models.IntegerField(default=1)),
                ('current_pick', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('active', 'Active'), ('completed', 'Completed')], default='setup', max_length=20)),
                ('scoring_format', models.CharField(choices=[('PPR', 'PPR'), ('HALF', 'Half PPR'), ('STD', 'Standard')], default='PPR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField()),
                ('round_number', models.IntegerField()),
                ('overall_pick', models.IntegerField()),
                ('is_user', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='draft.draftsession')),
            ],
            options={
                'ordering': ['overall_pick'],
                'unique_together': {('session', 'player'), ('session', 'overall_pick')},
            },
        ),
    ]
