# Generated by Django 4.2.23 on 2025-09-19 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.DeleteModel(
            name='UserPlayer',
        ),
    ]
