# Generated by Django 4.2.23 on 2025-11-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0003_alter_player_college_alter_player_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="number",
            new_name="height",
        ),
        migrations.RemoveField(
            model_name="player",
            name="college",
        ),
        migrations.AddField(
            model_name="player",
            name="depth_chart_position",
            field=models.CharField(
                choices=[
                    ("C", "Center"),
                    ("CB", "Cornerback"),
                    ("DB", "Defensive Back"),
                    ("DL", "Defensive Line"),
                    ("DT", "Defensive Tackle"),
                    ("FS", "Free Safety"),
                    ("G", "Offensive Guard"),
                    ("ILB", "Inside Linebacker"),
                    ("K", "Kicker"),
                    ("LB", "Linebacker"),
                    ("LS", "Long Snapper"),
                    ("MLB", "Middle Linebacker"),
                    ("NS", "Nose Tackle"),
                    ("OLB", "Outside Linebacker"),
                    ("P", "Punter"),
                    ("QB", "Quarterback"),
                    ("RB", "Running Back"),
                    ("SS", "Strong Safety"),
                    ("T", "Offensive Tackle"),
                    ("TE", "Tight End"),
                    ("WR", "Wide Receiver"),
                ],
                default=5,
                max_length=25,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACT", "Active"),
                    ("CUT", "Cut"),
                    ("DEV", "Practice Squad"),
                    ("INA", "Inactive"),
                    ("RES", "Reserve List"),
                ],
                default="INA",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="weight",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(
                choices=[
                    ("DB", "Defensive Back"),
                    ("DL", "Defensive Line"),
                    ("K", "Kicker"),
                    ("LB", "Linebacker"),
                    ("LS", "Long Snapper"),
                    ("OL", "Offensive Lineman"),
                    ("P", "Punter"),
                    ("QB", "Quarterback"),
                    ("RB", "Running Back"),
                    ("TE", "Tight End"),
                    ("WR", "Wide Receiver"),
                ],
                max_length=25,
            ),
        ),
    ]
