# Generated by Django 4.2.23 on 2025-11-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0006_alter_player_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="season",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
