# Generated by Django 4.2.23 on 2025-09-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('SCHED', 'Scheduled'), ('INPROG', 'InProgress'), ('FINAL', 'Final'), ('SUSP', 'Suspended'), ('POST', 'Postponed'), ('DELAY', 'Delayed'), ('CANCEL', 'Canceled'), ('FORF', 'Forfeit')], default='SCHED', max_length=20),
        ),
    ]
