# Generated by Django 4.2.23 on 2025-09-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_team_alternate_color_team_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="alternate_color",
        ),
        migrations.RemoveField(
            model_name="team",
            name="color",
        ),
    ]
