# Generated by Django 4.2.23 on 2025-11-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_team_players_delete_userteam"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Team_Players",
        ),
    ]
