# Generated by Django 4.2.23 on 2025-11-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
