# Generated by Django 4.2.23 on 2025-09-19 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballplayergamestat',
            name='completion_pct',
        ),
        migrations.RemoveField(
            model_name='footballplayergamestat',
            name='fantasy_points',
        ),
    ]
