# Generated by Django 4.2.23 on 2025-11-27 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0003_footballplayergamestat_fantasy_points_ppr_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="footballplayergamestat",
            old_name="sacks_yds_loss",
            new_name="sack_yards_loss",
        ),
    ]
