# Generated by Django 4.2.23 on 2025-11-27 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_delete_team_players'),
        ('players', '0007_player_season'),
        ('games', '0005_alter_game_away_score_alter_game_home_score_and_more'),
        ('stats', '0004_rename_sacks_yds_loss_footballplayergamestat_sack_yards_loss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footballplayergamestat',
            old_name='passing_touchdowns',
            new_name='pass_touchdowns',
        ),
        migrations.RenameField(
            model_name='footballplayergamestat',
            old_name='rushing_touchdowns',
            new_name='rush_touchdowns',
        ),
        migrations.AlterField(
            model_name='footballplayergamestat',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_game_id', to='games.game'),
        ),
        migrations.AlterField(
            model_name='footballplayergamestat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_id', to='players.player'),
        ),
        migrations.CreateModel(
            name='FootballTeamGameStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_attempts', models.PositiveIntegerField(default=0)),
                ('pass_completions', models.PositiveIntegerField(default=0)),
                ('pass_yards', models.IntegerField(default=0)),
                ('pass_tds', models.PositiveIntegerField(default=0)),
                ('rush_attempts', models.PositiveIntegerField(default=0)),
                ('rush_yards', models.IntegerField(default=0)),
                ('rush_touchdowns', models.PositiveIntegerField(default=0)),
                ('interceptions', models.PositiveIntegerField(default=0)),
                ('sacks', models.PositiveIntegerField(default=0)),
                ('fumbles', models.PositiveIntegerField(default=0)),
                ('fumbles_lost', models.PositiveIntegerField(default=0)),
                ('targets', models.PositiveIntegerField(default=0)),
                ('receptions', models.PositiveIntegerField(default=0)),
                ('receiving_yards', models.IntegerField(default=0)),
                ('receiving_touchdowns', models.IntegerField(default=0)),
                ('special_teams_touchdowns', models.PositiveIntegerField(default=0)),
                ('def_tackles_for_loss', models.PositiveIntegerField(default=0)),
                ('def_fumbles_forced', models.PositiveIntegerField(default=0)),
                ('def_sacks', models.PositiveIntegerField(default=0)),
                ('def_qb_hits', models.PositiveIntegerField(default=0)),
                ('def_interceptions', models.PositiveIntegerField(default=0)),
                ('def_touchdowns', models.PositiveIntegerField(default=0)),
                ('penalties', models.PositiveIntegerField(default=0)),
                ('penalty_yards', models.PositiveIntegerField(default=0)),
                ('fg_attempts', models.PositiveIntegerField(default=0)),
                ('fg_made', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_game_id', to='games.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_id', to='teams.team')),
            ],
        ),
    ]
