# Generated by Django 4.2.23 on 2025-11-27 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "stats",
            "0005_rename_passing_touchdowns_footballplayergamestat_pass_touchdowns_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="footballteamgamestat",
            old_name="pass_tds",
            new_name="pass_touchdowns",
        ),
    ]
