# Generated by Django 4.2.23 on 2025-12-31 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_rename_pass_tds_footballteamgamestat_pass_touchdowns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballteamgamestat',
            name='targets',
        ),
    ]
