# Generated by Django 4.2.23 on 2026-01-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0007_remove_footballteamgamestat_targets"),
    ]

    operations = [
        migrations.AddField(
            model_name="footballplayergamestat",
            name="air_yards",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="footballplayergamestat",
            name="redzone_carries",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="footballplayergamestat",
            name="redzone_rec_tds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="footballplayergamestat",
            name="redzone_receptions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="footballplayergamestat",
            name="redzone_rush_tds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="footballplayergamestat",
            name="redzone_targets",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="footballplayergamestat",
            name="snap_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="footballplayergamestat",
            name="snap_pct",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="footballplayergamestat",
            name="yards_after_catch",
            field=models.FloatField(default=0.0),
        ),
    ]
